---
linux_pkgs:
  - curl
  - wget
  - netcat
  - mtr
  - ncdu
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg
  - gnupg-agent
  - lsb-release
  - python3-pip
  - python3-apt
  - make
  - vim
  - htop
  - tree
  - jq
  - git
  - virtualbox
  - neofetch

bin_path: '/usr/local/bin'

terraform_src:
  'https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip'
vagrant_src:
  'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip'
vault_src:
  'https://releases.hashicorp.com/vault/1.11.1/vault_1.11.1_linux_amd64.zip'

docker_key:
  'https://download.docker.com/linux/debian/gpg'
docker_repo:
  'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
docker_compose_src:
  'https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64'

fish_config_file: '/home/{{ ansible_user_id }}/.config/fish/config.fish'

starship_src:
  'https://github.com/starship/starship/releases/download/v1.9.1/starship-x86_64-unknown-linux-musl.tar.gz'
starship_config_file:
  '/home/{{ansible_user_id }}/.config/starship.toml'
starship_cmd: 'starship init fish | source'
