---
- name: Installing and Updating common packages
  become: true
  block:
    - name: Upgrading all packages
      apt: 
        name: "*"
        state: latest

    - name: Installing Linux packages
      become: true
      apt:
        name: '{{ linux_pkgs }}'
        state: present
        update_cache: yes
        install_recommends: yes

    - name: Removing useless packages from the cache
      apt:
        autoclean: yes

    - name: Removing dependencies that are no longer required
      apt:
        autoremove: yes
