---
- name: Check if config.fish exists
  become: true
  stat:
    path: '{{ fish_config_file }}'
  register: fish_config

- name: Setting Starship Prompt 1.9.1
  become: true
  block:
    - name: Installing Starship 
      unarchive:
        src: '{{ starship_src }}'
        dest: /usr/local/bin/
        mode: 755
        group: root
        owner: root
        remote_src: yes

    - name: Configuring Starship
      template:
        src: './templates/starship.toml.j2'
        dest: '{{ starship_config_file }}'

- name: Setup config.fish file
  become: true
  template:
    src: './templates/config.fish.j2'
    dest: '{{ fish_config_file }}'
  when: fish_config.stat.exists
