---
- name: Setting Fish Shell
  become: true
  block:
    - name: Adding Fish repo
      apt_repository:
        repo: ppa:fish-shell/release-3

    - name: Installing Fish Shell 3.x
      apt:
        name: fish
        state: present

    - name: Changing Default Shell to Fish
      user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Ensure Fish config file are created
      become: true
      file:
        path: '{{ fish_config_file }}'
        state: touch

- name: Setting Starship Shell 1.9.1
  become: true
  block:
    - name: Installing Starship Minimal Shell
      unarchive:
        src: '{{ starship_src }}'
        dest: /usr/local/bin/
        mode: 755
        group: root
        owner: root
        remote_src: yes

    - name: Setup Fish to use Starship
      template:
        src: ./roles/terminal/templates/config.fish.j2
        dest: '{{ fish_config_file }}'

    - name: Configuring Starship
      template:
        src: ./roles/terminal/templates/starship.toml.j2
        dest: '{{ starship_config_file }}'

- name: Setup Neofetch
  become: true
  shell: 'echo neofetch >> {{ fish_config_file }}'
