---
linux_pkgs:
  - curl
  - wget
  - netcat
  - mtr
  - ncdu
  - unzip
  - apt-transport-https
  - ca-certificates
  - gnupg
  - gnupg-agent
  - lsb-release
  - python3-pip
  - python-apt
  - python3-apt
  - make
  - vim
  - htop
  - tree
  - jq
  - git
  - virtualbox
  - neofetch
